language: ruby
rvm:
  - 2.5.1
install: bundle install --jobs=3 --retry=3 --no-deployment
branches:
  only:
  - master
  - development
services:
- docker
before_install:
- sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*
- sudo apt-get update && sudo apt-get -y install curl unzip jq
- sudo curl -O https://releases.hashicorp.com/vault/1.0.1/vault_1.0.1_linux_amd64.zip
- sudo unzip vault_1.0.1_linux_amd64.zip
- sudo mv vault /usr/local/bin
- docker pull mongo:3.4
- docker tag mongo:3.4 mongo:latest
- docker run -d --name mongodb -p 27017:27017 mongo
script:
- bin/load_env_secrets.sh -p secret/kdux/scp/development/scp_config.json -s secret/kdux/scp/development/scp_service_account.json -e test
